# Generated by Django 5.1.1 on 2024-10-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovoTcc',
            fields=[
                ('id_novotcc', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('aluno1', models.CharField(max_length=255)),
                ('aluno2', models.CharField(max_length=255)),
                ('aluno3', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
                ('datafim', models.DateField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
